name: AI Search Optimization (Fixed)

on:
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  ai-optimization:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: AI Search Optimization Updates
        run: |
          # Simple AI platform presence updates
          mkdir -p public/ai-search
          
          # Update AI search metadata
          echo "Last AI optimization: $(date)" > public/ai-search/last-update.txt
          echo "AI platforms: ChatGPT, Claude, Gemini, Perplexity" > public/ai-search/platforms.txt
          
          # Update robots.txt for AI crawlers
          echo "" >> public/robots.txt
          echo "# AI Search Optimization - $(date)" >> public/robots.txt
          echo "User-agent: ChatGPT-User" >> public/robots.txt
          echo "Allow: /" >> public/robots.txt
          echo "User-agent: Claude-Web" >> public/robots.txt
          echo "Allow: /" >> public/robots.txt
          
          # Create simple AI-friendly sitemap
          echo '<?xml version="1.0" encoding="UTF-8"?>' > public/ai-sitemap.xml
          echo '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">' >> public/ai-sitemap.xml
          echo '  <url><loc>https://justlegalsolutions.com/</loc><priority>1.0</priority></url>' >> public/ai-sitemap.xml
          echo '  <url><loc>https://justlegalsolutions.com/services</loc><priority>0.9</priority></url>' >> public/ai-sitemap.xml
          echo '  <url><loc>https://justlegalsolutions.com/process-server-tulsa</loc><priority>0.9</priority></url>' >> public/ai-sitemap.xml
          echo '</urlset>' >> public/ai-sitemap.xml

      - name: Commit AI Optimization Updates
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git diff --staged --quiet || git commit -m "🤖 AI Search Optimization Update - $(date)"
          git push
          git push
