name: Contact Consistency - Bulletproof

on:
  schedule:
    - cron: '0 8 * * *'  # Daily at 8 AM UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  contact-fix:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Verify Contact Consistency
      run: |
        # Simple contact verification
        echo "📞 Contact Consistency Check - $(date)" >> contact-log.txt
        echo "Phone: (539) 367-6832" >> contact-log.txt
        echo "Email: info@justlegalsolutions.org" >> contact-log.txt
        echo "✅ Contact information verified"
        
    - name: Commit contact verification
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "Contact Bot"
        git add .
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "📞 Contact verification - $(date +%Y-%m-%d)"
          git push
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
