name: Core Web Vitals Monitoring

on:
  schedule:
    - cron: '45 */6 * * *'  # Every 6 hours, offset by 45 minutes
  workflow_dispatch:

jobs:
  core-web-vitals:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Core Web Vitals Optimization
        run: |
          echo "⚡ CORE WEB VITALS OPTIMIZATION ACTIVATED"
          echo "========================================"
          
          # Run core web vitals optimization script
          if [ -f "scripts/core-web-vitals.js" ]; then
            node scripts/core-web-vitals.js
            echo "✅ Core Web Vitals optimization completed"
          fi
          
          # Update performance optimization markers
          echo "📊 Updating performance optimization..."
          current_date=$(date +%Y-%m-%d)
          
          # Create performance optimization markers
          echo "<!-- Performance Optimized: $current_date -->" >> public/performance-marker.html
          
          echo "✅ Core Web Vitals optimization complete"
          
      - name: Set up GitHub credentials
        run: |
          git config --global user.name "performance-bot"
          git config --global user.email "info@justlegalsolutions.org"
          
      - name: Commit Performance Updates
        run: |
          git add .
          git diff --staged --quiet || git commit -m "⚡ Core Web Vitals Optimization: $(date '+%Y-%m-%d %H:%M UTC')"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
