name: Ultimate Ranking Blitz

on:
  schedule:
    - cron: '0 10 * * 1'  # Weekly Monday at 10 AM - SAFE frequency per expert recommendations
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  ranking-acceleration:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Run SEO Automation Scripts
        run: |
          echo "🚀 Starting Technical SEO Audit..."
          
          # REMOVED: Artificial timestamp updates (violates Google guidelines)
          # Per expert recommendations: Only update timestamps when content actually changes
          
          # Run manual SEO update if available
          if [ -f "manual-seo-update.js" ]; then
            node manual-seo-update.js
            echo "✅ SEO automation completed"
          fi
          
          # Run comprehensive test if available
          if [ -f "comprehensive-seo-test.js" ]; then
            node comprehensive-seo-test.js
            echo "✅ SEO validation completed"
          fi

      - name: Set up GitHub credentials
        run: |
          git config --global user.name "ranking-blitz-bot"
          git config --global user.email "info@justlegalsolutions.org"
          
      - name: Commit and Push Changes
        run: |
          git add .
          git diff --staged --quiet || git commit -m "🚀 Ultimate Ranking Blitz: $(date '+%Y-%m-%d %H:%M UTC')"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
