name: Voice Search - Bulletproof

on:
  schedule:
    - cron: '0 */12 * * *'  # Every 12 hours
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  voice-optimization:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Simple Voice Search Update
      run: |
        # Create simple voice search optimization
        echo "🎙️ Voice Search Update - $(date)" >> voice-search-log.txt
        
        # Update meta description for voice search
        echo "Voice search optimized: $(date)" > voice-search-status.txt
        
        # Simple voice search keywords update
        echo "# Voice Search Keywords Updated: $(date)" >> public/robots.txt
        echo "# Oklahoma process server, legal document delivery" >> public/robots.txt
        echo "# Same day service, licensed process servers" >> public/robots.txt
        
        echo "✅ Voice search optimization completed"
        
    - name: Commit voice search updates
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "Voice Search Bot"
        git add .
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "🎙️ Voice search update - $(date +%Y-%m-%d)"
          git push
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
